### ISSUE TITLE
Most Pages Broken on 1.39

### ISSUE THREAD

**Issue by HopperMCS** [Universal-Omega/Monaco#23]
Just did a clean install of 1.39. locally, and every Special page is basically broken, producing this error:

```
MediaWiki internal error.

Original exception: [bf2ce402c51d0446534a35ef] /mediawiki/index.php/Special:Preferences TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given
Backtrace:
from /var/www/html/mediawiki/skins/Monaco/includes/MonacoTemplate.php(1054)
#0 /var/www/html/mediawiki/skins/Monaco/includes/MonacoTemplate.php(1043): MonacoTemplate->printCustomPageBar()
#1 /var/www/html/mediawiki/skins/Monaco/includes/MonacoTemplate.php(997): MonacoTemplate->realPrintPageBar()
#2 /var/www/html/mediawiki/skins/Monaco/includes/MonacoTemplate.php(97): MonacoTemplate->printPageBar()
#3 /var/www/html/mediawiki/includes/skins/SkinTemplate.php(151): MonacoTemplate->execute()
#4 /var/www/html/mediawiki/includes/skins/SkinTemplate.php(177): SkinTemplate->generateHTML()
#5 /var/www/html/mediawiki/includes/OutputPage.php(2874): SkinTemplate->outputPage()
#6 /var/www/html/mediawiki/includes/MediaWiki.php(922): OutputPage->output()
#7 /var/www/html/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#8 /var/www/html/mediawiki/index.php(50): MediaWiki->run()
#9 /var/www/html/mediawiki/index.php(46): wfIndexMain()
#10 {main}

Exception caught inside exception handler: [bf2ce402c51d0446534a35ef] /mediawiki/index.php/Special:Preferences Error: Call to undefined method MonacoTemplate::getTitle()
Backtrace:
from /var/www/html/mediawiki/skins/Monaco/includes/MonacoTemplate.php(548)
#0 /var/www/html/mediawiki/skins/Monaco/includes/MonacoTemplate.php(34): MonacoTemplate->addVariables()
#1 /var/www/html/mediawiki/includes/skins/SkinTemplate.php(151): MonacoTemplate->execute()
#2 /var/www/html/mediawiki/includes/skins/SkinTemplate.php(177): SkinTemplate->generateHTML()
#3 /var/www/html/mediawiki/includes/OutputPage.php(2874): SkinTemplate->outputPage()
#4 /var/www/html/mediawiki/includes/exception/MWExceptionRenderer.php(183): OutputPage->output()
#5 /var/www/html/mediawiki/includes/exception/MWExceptionRenderer.php(102): MWExceptionRenderer::reportHTML()
#6 /var/www/html/mediawiki/includes/exception/MWExceptionHandler.php(131): MWExceptionRenderer::output()
#7 /var/www/html/mediawiki/includes/exception/MWExceptionHandler.php(248): MWExceptionHandler::report()
#8 /var/www/html/mediawiki/includes/MediaWiki.php(584): MWExceptionHandler::handleException()
#9 /var/www/html/mediawiki/index.php(50): MediaWiki->run()
#10 /var/www/html/mediawiki/index.php(46): wfIndexMain()
#11 {main}
```

**Comment by Universal-Omega** [comment]
What PHP version?

**Comment by HopperMCS** [comment]
By running ```php --version```:

```
PHP 8.1.7-1ubuntu3.2 (cli) (built: Jan 16 2023 15:18:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7-1ubuntu3.2, Copyright (c), by Zend Technologies
```

**Comment by Universal-Omega** [comment]
Not 100% fixed yet.

**Comment by Universal-Omega** [comment]
> By running `php --version`:
> 
> ```
> PHP 8.1.7-1ubuntu3.2 (cli) (built: Jan 16 2023 15:18:41) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.1.7, Copyright (c) Zend Technologies
>     with Zend OPcache v8.1.7-1ubuntu3.2, Copyright (c), by Zend Technologies
> ```

At least some if it was a PHP 8.1 issue. The two errors you mentioned at least should be fixed now. Let me know if different ones are occuring now. Thanks!

**Comment by HopperMCS** [comment]
That fixed it! You're the GOAT @Universal-Omega
